config/routes.rb
Lab2023web::Application.routes.draw do
  
  root :to => 'pages#index'

  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations =>  "admins/registrations"}
  namespace :admins do
    resources :dashboard
    resources :teams
    resources :projects do
      resources :project_pictures
    end
    resources :open_sources
  end

  resources :teams, :only => [:index]
  resources :projects, :only => [:index, :show]
  resources :open_sources, :only => [:index, :show]
  resources :pages, :only => [:index, :contact]

  match "/our-story" => "pages#stories", :as => "stories"
  match "/works" => "projects#index", :as => "works"
  match "/contact" => "pages#contact"
  match "/team" => "teams#index", :as => "teams"
  match "/open-source" => 'open_sources#index', :as => "open_sources"

  devise_for :users
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :description, :facebook_username, :github_username, :email, :name, :twitter_username, :avatar,
                  :position, :dudupress_username, :vidipanda_username

  validates_presence_of :description, :facebook_username, :github_username, :email, :name, :twitter_username,
                        :position, :dudupress_username, :vidipanda_username

  validates :email, :uniqueness => true

  has_attached_file :avatar,
                    :default_url => "/assets/missing-image.jpg",
                    :styles => {
                        :small => "200x200#",
                        :medium => "400x400#"
                    },
                    :path => "public/system/:class/:attachment/:style/:sef_file_name.:extension",
                    :url => "/system/:class/:attachment/:style/:sef_file_name.:extension"

  Paperclip.interpolates :sef_file_name do |attachment, style|
    attachment.instance.sef_file_name
  end

  def sef_file_name
    "#{id}-#{name.parameterize}"
  end

  validates_attachment :avatar, :presence => true
end

app/controllers/admins/teams_controller.rb
class Admins::TeamsController < Admins::ApplicationController
  def index
    @teams = Team.paginate(:page => params[:page])
    respond_with(:admins, @teams)
  end

  def show
    @team = Team.find(params[:id])
    respond_with(:admins, @team)
  end

  def new
    @team = Team.new
    respond_with(:admins, @team)
  end

  def edit
    @team = Team.find(params[:id])
  end

  def create
    @team = Team.new(params[:team])
    @team.save
    respond_with(:admins, @team)
  end

  def update
    @team = Team.find(params[:id])
    @team.update_attributes(params[:team])
    respond_with(:admins, @team)
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    respond_with(:admins, @team)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
    respond_with(@teams)
  end
end

app/helpers/admins/teams_helper.rb
module Admins::TeamsHelper
end

app/views/admins/teams/_form.html.haml
= simple_form_for([:admins, @team], :defaults => {:input_html => {:class => 'span12'}}) do |f|
  = f.error_notification
  .form-inputs
    .row-fluid
      .span8.well
        .row-fluid
          .span9
            = f.input :name
            = f.input :position
            = f.input :email
          .span3.thumbnail
            = image_tag(@team.avatar.url(:small))
            = f.input :avatar
          .clearfix
          = f.input :description, :input_html => {:rows => 3}
      .span4.well
        = f.input :github_username
        = f.input :vidipanda_username
        = f.input :dudupress_username
        = f.input :twitter_username
        = f.input :facebook_username

  .form-actions
    = f.button :submit

app/views/admins/teams/edit.html.haml
= title t('tt.edit', resource_name: Team.model_name.human)
- content_for :toolbar_left do
  = link_to(admins_teams_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/admins/teams/index.html.haml
= title t('tt.index', resource_name: Team.model_name.human)

- content_for :toolbar_left do
  = link_to(admins_dashboard_index_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
  = link_to(new_admins_team_path, class: 'btn', rel: 'tooltip', title: t('tooltips.new')) do
    %i.icon-plus

%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th= t('activerecord.attributes.team.name')
    %th= t('activerecord.attributes.team.position')
    %th= t('activerecord.attributes.team.email')
    %th{:width => "140px"}
  - @teams.each do |team|
    %tr
      %td= team.name
      %td= team.position
      %td= team.email
      %td
        = link_to(admins_team_path(team), class: 'btn', rel: 'tooltip', title: t('tooltips.show')) do
          %i.icon-eye-open
        = link_to(edit_admins_team_path(team) , class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
          %i.icon-pencil
        = link_to(admins_team_path(team), class: 'btn', confirm: t('confirm'), method: :delete, rel: 'tooltip', title: t('tooltips.delete')) do
          %i.icon-trash

%hr/
= will_paginate @teams

app/views/admins/teams/new.html.haml
= title t('tt.new', resource_name: Team.model_name.human)
- content_for :toolbar_left do
  = link_to(admins_teams_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/admins/teams/show.html.haml
= title t('tt.show', resource_name: Team.model_name.human)

- content_for :toolbar_left do
  = link_to(admins_teams_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
  = link_to(edit_admins_team_path(@team) , class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
    %i.icon-pencil
  = link_to(admins_team_path(@team), class: 'btn', confirm: t('confirm'), method: :delete, rel: 'tooltip', title: t('tooltips.delete')) do
    %i.icon-trash

.thumbnail.pull-right
  = image_tag(@team.avatar.url(:small))
= show_for @team do |s|
  = s.attribute :name
  = s.attribute :description
  = s.attribute :email
  = s.attribute :github_username
  = s.attribute :vidipanda_username
  = s.attribute :dudupress_username
  = s.attribute :twitter_username
  = s.attribute :facebook_username