config/routes.rb
Lab2023web::Application.routes.draw do
  
  root :to => 'pages#index'

  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations =>  "admins/registrations"}
  namespace :admins do
    resources :dashboard
    resources :teams
    resources :projects do
      resources :project_pictures
    end
    resources :open_sources
  end

  resources :teams, :only => [:index]
  resources :projects, :only => [:index, :show]
  resources :open_sources, :only => [:index, :show]
  resources :pages, :only => [:index, :contact]

  match "/our-story" => "pages#stories", :as => "stories"
  match "/works" => "projects#index", :as => "works"
  match "/contact" => "pages#contact"
  match "/team" => "teams#index", :as => "teams"
  match "/open-source" => 'open_sources#index', :as => "open_sources"

  devise_for :users
end

app/models/open_source.rb
class OpenSource < ActiveRecord::Base
  attr_accessible :facebook_page, :name, :repository_url, :twitter_username, :description

  validates_presence_of :name, :repository_url

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/controllers/admins/open_sources_controller.rb
class Admins::OpenSourcesController < Admins::ApplicationController
  def index
    @open_sources = OpenSource.paginate(:page => params[:page])
    respond_with(:admins, @open_sources)
  end

  def show
    @open_source = OpenSource.find(params[:id])
    respond_with(:admins, @open_source)
  end

  def new
    @open_source = OpenSource.new
    respond_with(:admins, @open_source)
  end

  def edit
    @open_source = OpenSource.find(params[:id])
  end

  def create
    @open_source = OpenSource.new(params[:open_source])
    @open_source.save
    respond_with(:admins, @open_source)
  end

  def update
    @open_source = OpenSource.find(params[:id])
    @open_source.update_attributes(params[:open_source])
    respond_with(:admins, @open_source)
  end

  def destroy
    @open_source = OpenSource.find(params[:id])
    @open_source.destroy
    respond_with(:admins, @open_source)
  end
end

app/controllers/open_sources_controller.rb
class OpenSourcesController < ApplicationController
  layout false, :only => [:show]
  def index
    @open_sources = OpenSource.order("id DESC")
    respond_with(@open_sources)
  end

  def show
    @open_source = OpenSource.find(params[:id])
    respond_with(@open_source)
  end
end

app/helpers/admins/open_sources_helper.rb
module Admins::OpenSourcesHelper
end

app/views/admins/open_sources/_form.html.haml
= simple_form_for([:admins, @open_source], :defaults => {:input_html => {:class => 'span12'}}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :repository_url
    = f.input :description, :input_html => {:rows => 3}
    = f.input :twitter_username
    = f.input :facebook_page

  .form-actions
    = f.button :submit

app/views/admins/open_sources/edit.html.haml
= title t('tt.edit', resource_name: OpenSource.model_name.human)
- content_for :toolbar_left do
  = link_to(admins_open_sources_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/admins/open_sources/index.html.haml
= title t('tt.index', resource_name: OpenSource.model_name.human)

- content_for :toolbar_left do
  = link_to(admins_dashboard_index_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
  = link_to(new_admins_open_source_path, class: 'btn', rel: 'tooltip', title: t('tooltips.new')) do
    %i.icon-plus

%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th
      = t('activerecord.attributes.open_source.name')
    %th
      = t('activerecord.attributes.open_source.repository_url')
    %th{:width => "140px"}
  - @open_sources.each do |open_source|
    %tr
      %td= open_source.name
      %td= open_source.repository_url
      %td
        = link_to(admins_open_source_path(open_source), class: 'btn', rel: 'tooltip', title: t('tooltips.show')) do
          %i.icon-eye-open
        = link_to(edit_admins_open_source_path(open_source) , class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
          %i.icon-pencil
        = link_to(admins_open_source_path(open_source), class: 'btn', confirm: t('confirm'), method: :delete, rel: 'tooltip', title: t('tooltips.delete')) do
          %i.icon-trash
%hr/
= will_paginate @open_sources

app/views/admins/open_sources/new.html.haml
= title t('tt.new', resource_name: OpenSource.model_name.human)
- content_for :toolbar_left do
  = link_to(admins_open_sources_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/admins/open_sources/show.html.haml
= title t('tt.show', resource_name: OpenSource.model_name.human)

- content_for :toolbar_left do
  = link_to(admins_open_sources_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
  = link_to(edit_admins_open_source_path(@open_source) , class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
    %i.icon-pencil
  = link_to(admins_open_source_path(@open_source), class: 'btn', confirm: t('confirm'), method: :delete, rel: 'tooltip', title: t('tooltips.delete')) do
    %i.icon-trash

= show_for @open_source do |s|
  = s.attribute :name
  = s.attribute :repository_url
  = s.attribute :twitter_username
  = s.attribute :facebook_page