config/routes.rb
Lab2023web::Application.routes.draw do
  
  root :to => 'pages#index'

  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations =>  "admins/registrations"}
  namespace :admins do
    resources :dashboard
    resources :teams
    resources :projects do
      resources :project_pictures
    end
    resources :open_sources
  end

  resources :teams, :only => [:index]
  resources :projects, :only => [:index, :show]
  resources :open_sources, :only => [:index, :show]
  resources :pages, :only => [:index, :contact]

  match "/our-story" => "pages#stories", :as => "stories"
  match "/works" => "projects#index", :as => "works"
  match "/contact" => "pages#contact"
  match "/team" => "teams#index", :as => "teams"
  match "/open-source" => 'open_sources#index', :as => "open_sources"

  devise_for :users
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :facebook_page, :name, :owner, :twitter_username, :website, :project_pictures_attributes, :cover

  has_many :project_pictures

  accepts_nested_attributes_for :project_pictures, :allow_destroy => true

  has_attached_file :cover,
                    :default_url => "/assets/missing-image.jpg",
                    :styles => {
                        :small => "250x250#"
                    },
                    :path => "public/system/:class/:attachment/:style/:sef_file_name.:extension",
                    :url => "/system/:class/:attachment/:style/:sef_file_name.:extension"

  validates_presence_of :description, :name, :owner, :website, :cover

  Paperclip.interpolates :sef_file_name do |attachment, style|
    attachment.instance.sef_file_name
  end

  def sef_file_name
    "#{id}-#{name.parameterize}"
  end

  extend FriendlyId

  friendly_id :name, use: [:slugged, :history]
end

app/controllers/admins/projects_controller.rb
class Admins::ProjectsController < Admins::ApplicationController
  def index
    @projects = Project.paginate(:page => params[:page])
    respond_with(:admins, @projects)
  end

  def show
    @project = Project.find(params[:id])
    respond_with(:admins, @project)
  end

  def new
    @project = Project.new
    respond_with(:admins, @project)
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])
    @project.save
    respond_with(:admins, @project)
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(params[:project])
    respond_with(:admins, @project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_with(:admins, @project)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    @project = Project.find(params[:id])
    respond_with(@project)
  end
end

app/helpers/admins/projects_helper.rb
module Admins::ProjectsHelper
end

app/views/admins/projects/_form.html.haml
= simple_form_for([:admins, @project], :html => {:multipart => true}, :defaults => {:input_html => {:class => 'span12'}}) do |f|
  = f.error_notification
  .row-fluid
    .span6.well
      .form-inputs
        = f.input :name
        = f.input :description
    .span6.well
      .form-inputs
        = f.input :website
        = f.input :owner, :collection => %w(lab2023 Müşteri)
        = f.input :twitter_username
        = f.input :facebook_page
        = f.input :cover
        %p Diğer Görseller
        %br/
        = file_field_tag('project_project_picture_image', multiple: true, name: "project[project_pictures_attributes][][image]")

  .form-actions
    .pull-right
      = f.button :submit

app/views/admins/projects/edit.html.haml
= title t('tt.edit', resource_name: Project.model_name.human)
- content_for :toolbar_left do
  = link_to(admins_projects_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/admins/projects/index.html.haml
= title t('tt.index', resource_name: Project.model_name.human)

- content_for :toolbar_left do
  = link_to(admins_dashboard_index_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
  = link_to(new_admins_project_path, class: 'btn', rel: 'tooltip', title: t('tooltips.new')) do
    %i.icon-plus

%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th
      =t('activerecord.attributes.project.name')
    %th
      =t('activerecord.attributes.project.website')
    %th{:width => "140px"}
  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.website
      %td
        = link_to(admins_project_path(project), class: 'btn', rel: 'tooltip', title: t('tooltips.show')) do
          %i.icon-eye-open
        = link_to(edit_admins_project_path(project) , class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
          %i.icon-pencil
        = link_to(admins_project_path(project), class: 'btn', confirm: t('confirm'), method: :delete, rel: 'tooltip', title: t('tooltips.delete')) do
          %i.icon-trash
%hr/
= will_paginate @projects

app/views/admins/projects/new.html.haml
= title t('tt.new', resource_name: Project.model_name.human)
- content_for :toolbar_left do
  = link_to(admins_projects_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/admins/projects/show.html.haml
= title t('tt.show', resource_name: Project.model_name.human)

- content_for :toolbar_left do
  = link_to(admins_projects_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
    Back
  = link_to(edit_admins_project_path(@project) , class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
    %i.icon-pencil
    Edit
  = link_to(admins_project_project_pictures_path(@project) , class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
    %i.icon-pencil
    Edit Pictures

= show_for @project do |s|
  = image_tag @project.cover(:small), :class => "thumbnail  pull-right"
  = s.attribute :name
  = s.attribute :description
  = s.attribute :website
  = s.attribute :owner
  = s.attribute :twitter_username
  = s.attribute :facebook_page

= render :partial => "admins/modal"