config/routes.rb
Lab2023web::Application.routes.draw do
  
  root :to => 'pages#index'

  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations =>  "admins/registrations"}
  namespace :admins do
    resources :dashboard
    resources :teams
    resources :projects do
      resources :project_pictures
    end
    resources :open_sources
  end

  resources :teams, :only => [:index]
  resources :projects, :only => [:index, :show]
  resources :open_sources, :only => [:index, :show]
  resources :pages, :only => [:index, :contact]

  match "/our-story" => "pages#stories", :as => "stories"
  match "/works" => "projects#index", :as => "works"
  match "/contact" => "pages#contact"
  match "/team" => "teams#index", :as => "teams"
  match "/open-source" => 'open_sources#index', :as => "open_sources"

  devise_for :users
end

app/views/layouts/admins/_nav.html.haml
%nav.navbar-inner
  %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  %a.brand{:href => "/"}
    lab2023 - Administration
  .nav-collapse
    %ul.nav
      %li
        = link_to admins_dashboard_index_path do
          %i.icon-home
          =t('nav.dashboard')
      %li
        = link_to(admins_teams_path) do
          %i.icon-user
          =t('nav.teams')
      %li
        = link_to(admins_projects_path) do
          %i.icon-briefcase
          =t('nav.projects')
      %li
        = link_to(admins_open_sources_path) do
          %i.icon-globe
          =t('nav.open_source')

    %ul.nav.pull-right
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          %i.icon-user
          = current_admin.name
          %b.caret
        %ul.dropdown-menu
          %li= link_to t('nav.profile'), edit_admin_registration_path
          %li= link_to t('nav.signout'), destroy_admin_session_path, :method => :delete

app/views/layouts/admins/application.html.haml
!!!5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title lab2023 - Administration | #{yield :title || "Hoşgeldiniz"}
    %meta{:content => "lab2023 - internet technologies", :name => "author"}/
    = stylesheet_link_tag "admins", "http://fonts.googleapis.com/css?family=PT+Sans", :media => "all"
    = javascript_include_tag "admins"
    = favicon_link_tag "favicon.png", :type => "image/png"
    = csrf_meta_tags
    = yield :head
  %body
    / Header
    - if current_admin
      %header.navbar.navbar-fixed-bottom
        = render :partial => "layouts/admins/nav"
    /Contents
    .container{:id => !current_admin ? "login" : "contents"}
      %h1.page-header= yield :title
      .wrapper.row-fluid
        .span12.wrap
          .head
            .span6.pull-left
              = yield :toolbar_left
            .span6.pull-right
              = yield :toolbar_right
            .clearfix
          / Messages
          = render :partial => "layouts/shared/messages"
          = yield